### PR TITLE
fix buff when dead

### LINKED ISSUE #8: Can cast .buff when dead
You can cast .buff when dead this presents a bad exploit where 2 players can solo things they shouldn’t if 1 dies he can spam .buff to heal the other player , can we make it so it cannot be cast while dead 💀

### PR DESCRIPTION
**Pull request by milestorme**
closes https://github.com/azerothcore/mod-buff-command/issues/8 update module to match skeleton, fix travis errors

### CODE REVIEW

File: src/BuffCommand.cpp [hunk 1]
```diff
@@ -53,7 +53,7 @@ class KargatumCS_BuffCOmmand : public CommandScript
 		}
 		else
 		{
-			if (player->duel || player->GetMap()->IsBattleArena() || player->HasFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH) || player->isDead(), player->IsInCombat() || player->IsInFlight())
```
Comment (BarbzYHOOL) [inline src/BuffCommand.cpp:56]: What was that bug? a typo?? @milestorme

**Comment by BarbzYHOOL** [comment]
plz, next time make two PRs, one for each feature/fix

One for the module chores (git etc), one for the issue fixed

Otherwise good job
